# Generated by Django 2.2.24 on 2021-12-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationFieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campo', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('temperatura_minima_local', models.SmallIntegerField()),
                ('temperatura_maxima_local', models.SmallIntegerField()),
                ('humedad_minima_local', models.SmallIntegerField()),
                ('humedad_maxima_local', models.SmallIntegerField()),
                ('tipo_suelo', models.CharField(max_length=50)),
                ('cultivo', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ConfigurationFieldModel',
            },
        ),
    ]
