# Generated by Django 2.2.24 on 2022-02-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationfieldmodel',
            name='latitud',
            field=models.IntegerField(default=-34.162418),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configurationfieldmodel',
            name='longitud',
            field=models.IntegerField(default=-58.959011),
            preserve_default=False,
        ),
    ]
