# Generated by Django 2.2.24 on 2022-02-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20220207_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationfieldmodel',
            name='latitud',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='configurationfieldmodel',
            name='longitud',
            field=models.FloatField(),
        ),
    ]
