# Generated by Django 2.2.24 on 2022-02-10 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_auto_20220207_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationfieldmodel',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='configurationfieldmodel',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='configurationfieldmodel',
            name='temperatura_maxima_local',
        ),
        migrations.RemoveField(
            model_name='configurationfieldmodel',
            name='temperatura_minima_local',
        ),
    ]
