# Generated by Django 2.2.24 on 2022-03-29 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_auto_20220209_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationfieldmodel',
            name='cantidad_sensores',
        ),
    ]
