# Generated by Django 2.2.24 on 2022-03-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_auto_20220329_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationfieldmodel',
            name='cantidad_sensores',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
