# Generated by Django 2.2.24 on 2022-03-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_auto_20220331_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationfieldmodel',
            name='cantidad_sensores',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
