# Generated by Django 2.2.24 on 2022-02-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricWeatherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature', models.FloatField()),
                ('temperature_min', models.FloatField()),
                ('temperature_max', models.FloatField()),
                ('precipitation', models.BooleanField()),
                ('precipitation_prob', models.FloatField()),
            ],
            options={
                'verbose_name': 'HistoricWeatherModel',
            },
        ),
    ]
