# Generated by Django 2.2.24 on 2021-12-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FutureWeatherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=25)),
                ('dia', models.DateField()),
                ('temperatura_minima', models.SmallIntegerField()),
                ('temperatura_maxima', models.SmallIntegerField()),
                ('humedad', models.SmallIntegerField()),
                ('precipitacion', models.BooleanField()),
                ('cantidad_precipitacion', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'FutureWeatherModel',
            },
        ),
        migrations.CreateModel(
            name='HistoricWeatherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=25)),
                ('dia', models.DateField()),
                ('temperatura_minima', models.SmallIntegerField()),
                ('temperatura_maxima', models.SmallIntegerField()),
                ('humedad_minima', models.SmallIntegerField()),
                ('humedad_maxima', models.SmallIntegerField()),
                ('precipitacion', models.BooleanField()),
                ('cantidad_precipitacion', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'HistoricWeatherModel',
            },
        ),
    ]
