# Generated by Django 2.2.24 on 2021-12-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futureweathermodel',
            old_name='temperatura_maxima',
            new_name='temperatura',
        ),
        migrations.RemoveField(
            model_name='futureweathermodel',
            name='cantidad_precipitacion',
        ),
        migrations.RemoveField(
            model_name='futureweathermodel',
            name='temperatura_minima',
        ),
        migrations.RemoveField(
            model_name='historicweathermodel',
            name='cantidad_precipitacion',
        ),
        migrations.AlterField(
            model_name='historicweathermodel',
            name='dia',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
