# Generated by Django 2.2.24 on 2022-02-10 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricWeatherModel',
        ),
    ]
