# Generated by Django 2.2.24 on 2021-12-04 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherAPI', '0002_auto_20211204_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicweathermodel',
            old_name='humedad_maxima',
            new_name='humedad',
        ),
        migrations.RemoveField(
            model_name='historicweathermodel',
            name='humedad_minima',
        ),
    ]
