# Generated by Django 2.2.24 on 2021-12-04 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weatherAPI', '0003_auto_20211204_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futureweathermodel',
            old_name='ciudad',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='futureweathermodel',
            old_name='humedad',
            new_name='humidity',
        ),
        migrations.RenameField(
            model_name='futureweathermodel',
            old_name='precipitacion',
            new_name='precipitation',
        ),
        migrations.RenameField(
            model_name='futureweathermodel',
            old_name='temperatura',
            new_name='temperature',
        ),
        migrations.RenameField(
            model_name='historicweathermodel',
            old_name='ciudad',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='historicweathermodel',
            old_name='dia',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='historicweathermodel',
            old_name='humedad',
            new_name='humidity',
        ),
        migrations.RenameField(
            model_name='historicweathermodel',
            old_name='precipitacion',
            new_name='precipitation',
        ),
        migrations.RenameField(
            model_name='historicweathermodel',
            old_name='temperatura_maxima',
            new_name='temperature',
        ),
        migrations.RenameField(
            model_name='historicweathermodel',
            old_name='temperatura_minima',
            new_name='temperature_max',
        ),
        migrations.RemoveField(
            model_name='futureweathermodel',
            name='dia',
        ),
        migrations.AddField(
            model_name='futureweathermodel',
            name='day',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicweathermodel',
            name='temperature_min',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
