# Generated by Django 2.2.24 on 2021-12-04 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherAPI', '0004_auto_20211204_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicweathermodel',
            name='day',
        ),
    ]
