# Generated by Django 2.2.24 on 2021-12-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherAPI', '0006_auto_20211204_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futureweathermodel',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='futureweathermodel',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historicweathermodel',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historicweathermodel',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historicweathermodel',
            name='temperature_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historicweathermodel',
            name='temperature_min',
            field=models.FloatField(),
        ),
    ]
