# Generated by Django 2.2.24 on 2022-02-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='irrigationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('duracion', models.SmallIntegerField()),
                ('cantidad_agua', models.SmallIntegerField()),
                ('humedad_antes', models.SmallIntegerField()),
                ('humedad_despues', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'irrigationHistoryModel',
                'verbose_name_plural': 'irrigationHistoryModels',
            },
        ),
    ]
