# Generated by Django 2.2.24 on 2022-02-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzyLogic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationhistory',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
