# Generated by Django 2.2.24 on 2022-02-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzyLogic', '0002_auto_20220210_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='irrigationHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('duracion_maxima', models.SmallIntegerField()),
                ('duracion', models.SmallIntegerField()),
                ('cantidad_agua', models.SmallIntegerField()),
                ('humedad_antes', models.SmallIntegerField()),
                ('humedad_despues', models.SmallIntegerField()),
                ('temperatura', models.SmallIntegerField()),
                ('numero_paso', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'irrigationHistoryModel',
                'verbose_name_plural': 'irrigationHistoryModels',
            },
        ),
        migrations.DeleteModel(
            name='irrigationHistory',
        ),
    ]
