# Generated by Django 2.2.24 on 2022-01-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='irrigationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automatico', models.BooleanField(default=0)),
                ('encendido', models.BooleanField(default=0)),
                ('riego_diurno', models.BooleanField(default=0)),
                ('tiempo_maximo_riego', models.TimeField(default=60)),
                ('envio_alertas', models.BooleanField(default=1)),
                ('cantidad_dias_sin_lluvia', models.SmallIntegerField(default=4)),
            ],
            options={
                'verbose_name': 'irrigationModel',
                'verbose_name_plural': 'irrigationModels',
            },
        ),
    ]
