# Generated by Django 2.2.24 on 2022-01-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationmodel',
            name='automatico',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='irrigationmodel',
            name='cantidad_dias_sin_lluvia',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='irrigationmodel',
            name='encendido',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='irrigationmodel',
            name='envio_alertas',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='irrigationmodel',
            name='riego_diurno',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='irrigationmodel',
            name='tiempo_maximo_riego',
            field=models.TimeField(),
        ),
    ]
