# Generated by Django 2.2.24 on 2022-01-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0002_auto_20220116_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationmodel',
            name='automatico',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='irrigationmodel',
            name='encendido',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='irrigationmodel',
            name='envio_alertas',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='irrigationmodel',
            name='riego_diurno',
            field=models.CharField(max_length=4),
        ),
    ]
