# Generated by Django 2.2.24 on 2022-01-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0003_auto_20220116_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationmodel',
            name='tiempo_maximo_riego',
            field=models.SmallIntegerField(),
        ),
    ]
