# Generated by Django 2.2.24 on 2022-01-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0004_auto_20220116_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='irrigationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('duracion', models.SmallIntegerField()),
                ('cantidad_agua', models.SmallIntegerField()),
                ('humedad_antes', models.SmallIntegerField()),
                ('humedad_despues', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'irrigationModel',
                'verbose_name_plural': 'irrigationModels',
            },
        ),
    ]
