# Generated by Django 2.2.24 on 2022-01-30 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0005_irrigationhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='irrigationhistory',
            options={'verbose_name': 'irrigationHistoryModel', 'verbose_name_plural': 'irrigationHistoryModels'},
        ),
    ]
