# Generated by Django 2.2.24 on 2022-01-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0006_auto_20220130_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationhistory',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
