# Generated by Django 2.2.24 on 2022-02-05 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0007_auto_20220130_1802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='irrigationHistory',
        ),
    ]
