# Generated by Django 2.2.24 on 2022-03-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0008_delete_irrigationhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationmodel',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
